---
title: "R Notebook"
output: html_notebook_Q3
---


```{r}
#library(lme4)
library(ggplot2)
library(ggpubr)
library(lmerTest)
library(dplyr)
library(magrittr)
library(car)

require(GGally)
require(reshape2)
require(lme4)
require(compiler)
require(parallel)
#require(boot)
library(tidyverse)
library(MuMIn)
require(optimx)

require(lattice)

library(chron)
library(simr)
library(broom)
```

Create output files
```{r}
path_to_data = "/Users/margieruffin/Desktop/Research/New Disinfo/Results/Data Collection 3/Fixed LMER/"

response_file = "responses.csv"

output_results = file.path(path_to_data, response_file)
print(output_results)

setwd(path_to_data)

#Read in data
all_reponses <- read.csv(output_results)
all_reponses <- na.omit(all_reponses)

print(all_reponses)
summary(all_reponses)

```

Clean up the data
```{r}
#use this section to clean up the data

 clean_data <- function(data) {
   data <- na.omit(data)
   head(data)
   
   data %<>%
      mutate(Cond = as.numeric(Condition),
             Cond = if_else(Condition == "1", 1, Cond),
             Cond = if_else(Condition == "2", 2, Cond),
             Cond = if_else(Condition == "3", 3, Cond))
     data$Condition <- factor(data$Condition)

   #Mutate All Accuracy for Tweets
    data %<>%
      mutate(TweetAcc = as.double(TweetAccuracy),
             TweetAcc = if_else(TweetAccuracy == "Very Inaccurate (1)", -2, TweetAcc),
             TweetAcc = if_else(TweetAccuracy == "Somewhat Inaccurate (2)", -1, TweetAcc),
             TweetAcc = if_else(TweetAccuracy == "Neither Accurate nor Inaccurate (3)", 0, TweetAcc),
             TweetAcc = if_else(TweetAccuracy == "Somewhat Accurate (4)", 1, TweetAcc),
             TweetAcc = if_else(TweetAccuracy == "Very Accurate (5)", 2, TweetAcc))
   data$TweetAccuracy <- factor(data$TweetAccuracy)
  
    data %<>%
      mutate(TPAcc = as.double(TPAccuracy),
             TPAcc = if_else(TPAccuracy == "Very Inaccurate (1)", -2, TPAcc),
             TPAcc = if_else(TPAccuracy == "Somewhat Inaccurate (2)", -1, TPAcc),
             TPAcc = if_else(TPAccuracy == "Neither Accurate nor Inaccurate (3)", 0, TPAcc),
             TPAcc = if_else(TPAccuracy == "Somewhat Accurate (4)", 1, TPAcc),
             TPAcc = if_else(TPAccuracy == "Very Accurate (5)", 2, TPAcc))
     data$TPAccuracy <- factor(data$TPAccuracy)
    
    
    #--------------------------------------------------------------------------------------------------
    
   #Mutate All Engagements --- For plots not regression
   data %<>%
     mutate(TweetEng = as.numeric(TweetEngage),
            TweetEng = if_else(TweetEngage == "Like", 1, TweetEng),
            TweetEng = if_else(TweetEngage == "Retweet", 1, TweetEng),
            TweetEng = if_else(TweetEngage == "Reply", 1, TweetEng),
            TweetEng = if_else(TweetEngage == "External Share", 1, TweetEng),
            TweetEng = if_else(TweetEngage == "No Engagement", 0, TweetEng),
            TweetEng = if_else(TweetEngage == "Prefer not to say", 0, TweetEng))
    data$TweetEngage <- factor(data$TweetEngage)

   data %<>%
     mutate(TPEng = as.numeric(TPEngage),
            TPEng = if_else(TPEngage == "Like", 1, TPEng),
            TPEng = if_else(TPEngage == "Retweet", 1, TPEng),
            TPEng = if_else(TPEngage == "Reply", 1, TPEng),
            TPEng = if_else(TPEngage == "External Share", 1, TPEng),
            TPEng = if_else(TPEngage == "No Engagement", 0, TPEng),
            TPEng = if_else(TPEngage == "Prefer not to say", 0, TPEng))
    data$TPEngage <- factor(data$TPEngage)
    
    #--------------------------------------------------------------------------------------------------
    #Mutate All Fake Profile Ratings
    data %<>%
      mutate(FakeRateProf = as.double(FakeRate),
             FakeRateProf = if_else(FakeRate == "Definitely fake (1)", -2, FakeRateProf),
             FakeRateProf = if_else(FakeRate == "More fake than real (2)", -1, FakeRateProf),
             FakeRateProf = if_else(FakeRate == "I'm not sure (3)", 0, FakeRateProf),
             FakeRateProf = if_else(FakeRate == "More real than fake (4)",1, FakeRateProf),
             FakeRateProf = if_else(FakeRate == "Definitely real (5)", 2, FakeRateProf))
    data$FakeRate <- factor(data$FakeRate)

    #--------------------------------------------------------------------------------------------------
    #Mutate All Fake Profile Ratings

    data %<>%
      mutate(photoshop = as.character(Photoshop),
             photoshop = if_else(Photoshop == "Yes, very experienced", "yes experience", photoshop),
             photoshop = if_else(Photoshop == "Yes, somewhat experienced", "yes experience", photoshop),
             photoshop = if_else(Photoshop == "Yes, but I just started using it", "yes experience", photoshop),
             photoshop = if_else(Photoshop == "No, I've never used it", "no experience", photoshop),
             photoshop = if_else(Photoshop == "Prefer not to say", "no experience", photoshop))
    data$Photoshop <- factor(data$Photoshop)
    
    data %<>%
      mutate(political = as.character(Political_View),
             political = if_else(Political_View == "Very Liberal", "liberal", political),
             political = if_else(Political_View == "Slightly Liberal", "liberal", political),
             political = if_else(Political_View == "Slightly Conservative", "conservative", political),
             political = if_else(Political_View == "Very Conservative", "conservative", political),
             political = if_else(Political_View == "Prefer not to say", "conservative", political))
    data$Political_View <- factor(data$Political_View)

    data %<>%
      mutate(trust = as.character(Trust_Tweet),
             trust = if_else(Trust_Tweet == "Untrustworthy 1", "not trusting", trust),
             trust = if_else(Trust_Tweet == "2", "not trusting", trust),
             trust = if_else(Trust_Tweet == "3", "not trusting", trust),
             trust = if_else(Trust_Tweet == "4", "not trusting", trust),
             trust = if_else(Trust_Tweet == "Neutral 5", "neutral", trust),
             trust = if_else(Trust_Tweet == "6", "trusting", trust), 
             trust = if_else(Trust_Tweet == "7", "trusting", trust), 
             trust = if_else(Trust_Tweet == "8", "trusting", trust), 
             trust = if_else(Trust_Tweet == "9", "trusting", trust), 
             trust = if_else(Trust_Tweet == "Trustworthy 10", "trusting", trust))
    data$Trust_Tweet <- factor(data$Trust_Tweet)
    
   
  data$TweetEng <-factor(data$TweetEng)
  data$TPEng <-factor(data$TPEng)
  
  data$Age <- factor(data$Age)
  data$TweetEngage <- factor(data$TweetEngage)
  data$TPEngage <- factor(data$TPEngage)
  data$Political_View <- factor(data$Political_View)
  data$Trust_Tweet <- factor(data$Trust_Tweet)
  data$TweetID <- factor(data$TweetID)
  
  data$photoshop <- factor(data$photoshop)
  data$trust <- factor(data$trust)
  data$political <- factor(data$political)
  
  
   #Mutate Age??
   # data %<>%
   #   mutate(Age.0 = as.numeric(Age),
   #          Age.0 = if_else(Age == 'Under 18', 0, Age.0),
   #          Age.0 = if_else(Age == '18-24', 1, Age.0),
   #          Age.0 = if_else(Age == '25-34', 2, Age.0),
   #          Age.0 = if_else(Age == '35-44', 3, Age.0),
   #          Age.0 = if_else(Age == '45-54', 4, Age.0),
   #          Age.0 = if_else(Age == '55-64', 5, Age.0),
   #          Age.0 = if_else(Age == '65+', 6, Age.0))
           
   #data$Age.0 <- factor(data$Age.0)
   
   #Mutate Gender??
   # data %<>%
   #   mutate(Gender.0 = as.character(Gender),
   #          Gender.0 = if_else(Gender == 'Male', '0Male', Gender.0),
   #          Gender.0 = if_else(Gender == 'Female', '1Female', Gender.0),
   #          Gender.0 = if_else(Gender == 'Other', '2Other', Gender.0),
   #          Gender.0 = if_else(Gender == 'Prefer not to say', '2Other', Gender.0),
   #          Gender.0 = if_else(Gender == '', '2Other', Gender.0))
   #data$Gender <- factor(data$Gender)
    
   #Mutate Education
   #data$Education <- factor(data$Education)

 return(data)
 }
 
 CleanRespones <- clean_data(all_reponses)

 print(CleanRespones)

 # print (CleanRespones[CleanRespones$Condition == "1", ])
```

```{r}
print("Tweet Accuracy Mean")
aggregate(CleanRespones$TweetAcc, list(CleanRespones$Condition), FUN=mean)
aggregate(CleanRespones$TweetAcc, list(CleanRespones$Condition), FUN=median)

print(NULL)

print("Tweet + Profile Mean")
aggregate(CleanRespones$TPAcc, list(CleanRespones$Condition), FUN=mean)
aggregate(CleanRespones$TPAcc, list(CleanRespones$Condition), FUN=median)

print("Fake Profole Rate")
aggregate(CleanRespones$FakeRateProf, list(CleanRespones$Condition), FUN=mean)
aggregate(CleanRespones$FakeRateProf, list(CleanRespones$Condition), FUN=median)

```




```{r}
boxplot(TweetAcc ~ Condition, CleanRespones, col = c("deepskyblue"), xlab = "Condition", ylab = "Tweet Accuracy", font.lab = 2, col.lab = "Black", cex.lab = 1.5)

boxplot(TPAcc ~ Condition ,CleanRespones, col = c("deepskyblue"))

#boxplot(FakeRateProf ~ Condition ,CleanRespones, col = c("deepskyblue"))

cols = c("lightgreen", "firebrick2" , "deepskyblue")
count <- table(CleanRespones$Condition, CleanRespones$TweetEngage)
count1 <- table(CleanRespones$Condition, CleanRespones$TPEngage)

barplot(count, col = cols, xlab = "Engagement Type", ylab = "Count", font.lab = 2, col.lab = "Black", cex.lab = 1.5, legend.text = TRUE)
barplot(count1, col = cols, xlab = "Engagement Type", ylab = "Count", font.lab = 2, col.lab = "Black", cex.lab = 1.5, legend.text = TRUE)
```


RQ3 Comparing Accuracy
```{r}
data = CleanRespones
CleanRespones <- within(CleanRespones, Condition <- relevel(Condition, ref = "2"))
response.model = lmer(TPAcc ~ Condition + (1|Subject) + (1|TweetID)  ,data , REML = FALSE)
 
summary(response.model)
#anova(response.model)
```
RQ3: Acc With Trust
```{r}
data = CleanRespones
CleanRespones <- within(CleanRespones, Condition <- relevel(Condition, ref = "2"))
response.model = lmer(TPAcc ~ Condition + trust + (1|Subject) + (1|TweetID)  ,data , REML = FALSE)
 
summary(response.model)
#anova(response.model)
```

RQ3 Acc with political view
```{r}
data = CleanRespones
CleanRespones <- within(CleanRespones, Condition <- relevel(Condition, ref = "2"))
response.model = lmer(TPAcc ~ Condition + political + (1|Subject) + (1|TweetID)  ,data , REML = FALSE)
 
summary(response.model)
#anova(response.model)
```

RQ3 Acc with Photoshop experience
```{r}
data = CleanRespones
CleanRespones <- within(CleanRespones, Condition <- relevel(Condition, ref = "2"))
response.model = lmer(TPAcc ~ Condition + photoshop + (1|Subject) + (1|TweetID)  ,data , REML = FALSE)
 
summary(response.model)
#anova(response.model)
```


RQ 3 Eng
```{r}

data = CleanRespones
#response.model = glmer(TPEng ~ Condition + (1|Subject) , family=binomial, data) #+ (1|TweetID)
response.model = glmer(TPEng ~ Condition + (1|Subject) , family=binomial, data,control = glmerControl(optimizer ="bobyqa"))

summary(response.model)
#allFit(response.model)

```
RQ3 Eng with trust
```{r}
data = CleanRespones
#response.model = glmer(TPEng ~ Condition + (1|Subject) , family=binomial, data) #+ (1|TweetID)
response.model = glmer(TPEng ~ Condition * trust + (1|Subject) , family=binomial, data,control = glmerControl(optimizer ="bobyqa"))

summary(response.model)
#allFit(response.model)
```
 
RQ3 Eng with political view
```{r}
data = CleanRespones
response.model = glmer(TPEng ~ Condition * political + (1|Subject) , family=binomial, data,control = glmerControl(optimizer ="bobyqa"))

summary(response.model)
#allFit(response.model)
```
 
RQ3 Eng with Photoshop experience 
```{r}
data = CleanRespones
response.model = glmer(TPEng ~ Condition * photoshop + (1|Subject) , family=binomial, data,control = glmerControl(optimizer ="bobyqa"))

summary(response.model)
#allFit(response.model)
```


RQ3 Profile Auth
```{r}
data = CleanRespones

response.model = lmer(FakeRateProf  ~ Condition + (1|Subject), data, REML = FALSE)

summary(response.model)
#anova(response.model)
```
RQ3 Auth with trust
```{r}
data = CleanRespones

response.model = lmer(FakeRateProf ~ Condition + trust + (1|Subject), data, REML = FALSE)

summary(response.model)
#anova(response.model)
```

RQ3 Auth with political view
```{r}
data = CleanRespones

response.model = lmer(FakeRateProf ~ Condition + political + (1|Subject), data, REML = FALSE)

summary(response.model)
#anova(response.model)
```

RQ3 Auth with Photoshop experience
```{r}
data = CleanRespones

response.model = lmer(FakeRateProf ~ Condition + photoshop + (1|Subject), data, REML = FALSE)

summary(response.model)
#anova(response.model)
```

```{r}
# CleanRespones <- within(CleanRespones, TweetEngage <- relevel(TweetEngage, ref = "No Engagement"))
# response.model = lmer(TweetAcc ~ Condition + TweetEngage + (1|Subject) , data=CleanRespones)
# 
# summary(response.model)
```
